### Java中的异常处理

```
//当除数为0时的异常问题
public class Exception1 {
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		System.out.println("请输入两个整数：");
		int a = sc.nextInt();
		int b = sc.nextInt();
		//关键字：try：运行代码，代码块中是可能出现异常的代码；catch:捕获异常，参数是异常对象，输出异常信息
		//finally:无论是否发生异常，try代码块的内容都会被执行，一般用于资源释放
		//throw:用于catch内，手动抛出异常，即抛给调用本方法的对象。
		try {
			int c = a/b;
			System.out.println("a+b="+c);
		}catch(Exception e) {
			System.out.println("发生异常！异常信息是"+e.getMessage());
			//throw e;
		}finally {
			System.out.println("无论是否发生异常，这里面的内容都会被执行，一般用于资源释放");
			
		}
		System.out.println("程序执行结束。");
	}
}
```
