### Java中的异常处理
### 关键字：
- try：运行代码，代码块中是可能出现异常的代码；
- catch:捕获异常，参数是异常对象，输出异常信息;catch代码块可出现多个，但顺序是先子类后父类（小异常放前面，总异常放后面）。
- finally:无论是否发生异常，try代码块的内容都会被执行，一般用于资源释放；
	不执行的情况：（在catch代码块中，使用system.exit(0)时，终止jvm运行，程序终止）
- throw:用于在程序内抛出异常，抛给调用者
- throws: 关键字，标明方法可能抛出异常。
```
//当除数为0时的异常问题
public class Exception1 {
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		System.out.println("请输入两个整数：");
		int a = sc.nextInt();
		int b = sc.nextInt();
		
		//throw:用于catch内，手动抛出异常，即抛给调用本方法的对象。
		try {
			int c = a/b;
			System.out.println("a+b="+c);
		}catch(Exception e) {
			System.out.println("发生异常！异常信息是"+e.getMessage());
			//throw e;
		}finally {
			System.out.println("无论是否发生异常，这里面的内容都会被执行，一般用于资源释放");
			
		}
		System.out.println("程序执行结束。");
	}
}
```
